backend:
  name: [github]
  repo: ComradeAERGO/aergo
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://aergo.vercel.app/
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accessed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{id}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}
